[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.history-search-multi-word]
github = "zdharma-continuum/history-search-multi-word"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-users--zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.hamadakafu--zsh-completions]
github = "hamadakafu/zsh-completions"

[plugins.typewritten]
github = "reobin/typewritten"

