snippet Rust "Rust with BuildKit" b
FROM rust:1.55.0

WORKDIR /app

ARG bin_name="toolbox-web"
COPY . .

# cacheはbuild kitが勝手に削除する
RUN --mount=type=cache,target=/usr/local/cargo/registry \
  --mount=type=cache,target=/app/target \
  cargo build --release && \
  cp /app/target/release/${bin_name} /app/main

ENTRYPOINT ["/app/main"]
endsnippet
