snippet Rust "Rust with BuildKit" b
FROM rust:1.48.0

WORKDIR /app

COPY . .

# cacheはbuild kitが勝手に削除する
RUN --mount=type=cache,target=/usr/local/cargo/registry \
  --mount=type=cache,target=/app/target \
  cargo build --release && \
	cp /app/target/release/server /app/server

ENTRYPOINT ["/app/server"]
endsnippet
