on:
  push:
    branches:
      - master
name: Build C++ Development Env
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.cpp.dev
        push: false
