on: workflow_dispatch
name: Build Image for Development Env
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
